apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    network.harvesterhci.io/route: '{"connectivity":"true"}'
  creationTimestamp: '2024-10-10T18:02:27Z'
  finalizers:
    - wrangler.cattle.io/harvester-network-nad-controller
    - wrangler.cattle.io/harvester-network-manager-nad-controller
  generation: 4
  labels:
    network.harvesterhci.io/clusternetwork: cluster-1
    network.harvesterhci.io/ready: 'true'
    network.harvesterhci.io/type: L2VlanNetwork
    network.harvesterhci.io/vlan-id: '1'
  managedFields:
    - apiVersion: k8s.cni.cncf.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:config: {}
      manager: harvester
      operation: Update
      time: '2024-10-14T17:42:53Z'
    - apiVersion: k8s.cni.cncf.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:network.harvesterhci.io/route: {}
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/harvester-network-manager-nad-controller": {}
            v:"wrangler.cattle.io/harvester-network-nad-controller": {}
          f:labels:
            .: {}
            f:network.harvesterhci.io/clusternetwork: {}
            f:network.harvesterhci.io/ready: {}
            f:network.harvesterhci.io/type: {}
            f:network.harvesterhci.io/vlan-id: {}
      manager: harvester-network-controller
      operation: Update
      time: '2024-10-16T13:06:37Z'
  name: vlan104
  namespace: default
  resourceVersion: '6919317'
  uid: 8d0b540b-8be1-4710-b80b-41f74703bac4
spec:
  config: >-
    {"cniVersion":"0.3.1","name":"vlan104","type":"bridge","bridge":"cluster-1-br","promiscMode":true,"vlan":1,"ipam":{"type":
    "kube-ovn", "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
    "provider": "vlan104.default"}}
